#!/bin/bash

#This script take a set of bursts generated by a particular set of meta parameters and separates them into a groups of three to then be passed to the python script for wavelet analysis.'

#Define meta parameters
#MTOT=($(shuf -i 20-80 -n 5))
MTOT=( 57 61 69 76 77 )
MASS_RATIO=0.3
DESTAR=0.2
TSTAR=-4.0


#Define time window
TMIN=-8
TMAX=0

#generate bursts for the random masses
for ii in ${MTOT[@]} ; do
     OUTDIR='../wavelet_mcmc_data/kombine_eccprior/all_meta/triple_wavelet/batch_tests/redo_batch_tests/mtot_'${ii}'/'
     if [ -d ${OUTDIR} ] && echo "Directory ${OUTDIR}" ; then
         continue
     else
         mkdir ${OUTDIR}
         python burst_generator.py -o ${OUTDIR} -m $ii -q ${MASS_RATIO} --destar ${DESTAR} --tstar ${TSTAR} --tmin ${TMIN} --tmax ${TMAX}
     fi
     
    #Count the number of bursts in the file
    pushd ${OUTDIR}
    BURSTS=(`wc -l 'bursts.dat'`)

    idx=0
    while [[ ${idx} -le $(( ${BURSTS[0]}-1 )) ]] ; do
            
        RUNDIR='run'${idx}'/'
        mkdir ${RUNDIR}
        pushd ${RUNDIR}
            	
        python /home/bcheeseboro/eccprior_proj/Current\ research\ stuff/code/ecc_prior/wavelet_mcmc_code/triple_wavelet_testing_all_meta_eccprior_kombine_v2.py -m ${ii} -q ${MASS_RATIO} --anchor_idx ${idx} --tmin ${TMIN} --tmax ${TMAX} --burst_file ../bursts.dat 
        popd

        (( idx=idx+1 ))
    done
    popd
done  



